version: "3"
services:
 build_tool:
  image: maven:latest
  volumes: ["./:/mymaven"]
  command: bash -c "cd /mymaven && mvn package"
 web:
  image: raghu/tc
  deploy:
   replicas: 5
  ports:
   - 80:8080
  networks:
   - webnet
networks:
 webnet:
